Números Complejos: complex_number Class Reference
complex_number Class Reference
#include <complejo.h>
Public Member Functions
complex_number (double first_part, double second_part)
double add (complex_number &complex1, complex_number &complex2)
La función add suma por separado la parte real y la parte imaginaria y luego hace lo mismo que la función print para indicar cual es el resultado de la operación.
double sub (complex_number &complex1, complex_number &complex2)
La función sub hace el mismo funcionamiento que la add pero en este caso en vez de sumar resta y tiene en cuenta si el número es negativo o positivo.
void print ()
La función print, agrupa la parte real y imaginaria del número para ponerlo en una frase que te indica cual es el número complejo con el que estas operando.
Private Attributes
double real
double imaginary
Detailed Description
Definition at line 13 of file complejo.h.
Constructor & Destructor Documentation
complex_number()
complex_number::complex_number (double first_part, double second_part)
Definition at line 17 of file complejo.cc.
References imaginary, real, and result.
{
   real = first_part;
   imaginary = second_part;
 }
Member Function Documentation
add()
double complex_number::add (complex_number & complex1, complex_number & complex2)
La función add suma por separado la parte real y la parte imaginaria y luego hace lo mismo que la función print para indicar cual es el resultado de la operación.
Finalmente en el return suma estos dos para que cuando pase el test poder comprobar que funciona bien.
Definition at line 34 of file complejo.cc.
References imaginary, and real.
Referenced by main(), and TEST().
{
   result.real = (complex1.real + complex2.real);
   result.imaginary = (complex1.imaginary + complex2.imaginary);
   std::cout << "Suma = " << result.real << " + " << result.imaginary <<"i"<< std::endl;
   return result.real + result.imaginary;
 }
print()
void complex_number::print ()
La función print, agrupa la parte real y imaginaria del número para ponerlo en una frase que te indica cual es el número complejo con el que estas operando.
Definition at line 27 of file complejo.cc.
References imaginary, and real.
Referenced by main().
{
   std::cout << " Número Complejo = " << real << " + " << imaginary << "i" << std::endl;
 }
sub()
double complex_number::sub (complex_number & complex1, complex_number & complex2)
La función sub hace el mismo funcionamiento que la add pero en este caso en vez de sumar resta y tiene en cuenta si el número es negativo o positivo.
Definition at line 44 of file complejo.cc.
References imaginary, and real.
Referenced by main(), and TEST().
{
   result.real = (complex1.real - complex2.real);
   result.imaginary = (complex1.imaginary - complex2.imaginary);
   if (result.imaginary < 0){
     std::cout << "Resta = " << result.real << result.imaginary << "i" << std::endl;
   }else{
     std::cout << "Resta = " << result.real << " + " << result.imaginary << "i" << std::endl;
   }
   return result.real + result.imaginary;
 }
Member Data Documentation
imaginary
double complex_number::imaginary private
Definition at line 21 of file complejo.h.
Referenced by add(), complex_number(), print(), and sub().
real
double complex_number::real private
Definition at line 20 of file complejo.h.
Referenced by add(), complex_number(), print(), and sub().
The documentation for this class was generated from the following files:
src/complejo.h
src/complejo.cc