Números Complejos: src/complejo_main.cc File Reference
complejo_main.cc File Reference
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
#include <iostream>
#include "complejo.h"
Functions
int main ()
Detailed Description
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Author
Alejandro García Bautista
Date
27/12/20 Programa que suma y resta dos complejos. Si se desea cambiar los datos de los números complejos solo hay que modificarlos desde este archivo y despues ir a la carpeta build y ejecutar el comando make nuevamente.
Bug:
Ninguno conocido por el momento.
Definition in file complejo_main.cc.
Function Documentation
main()
int main ()
Definition at line 19 of file complejo_main.cc.
References complex_number::add(), complex_number::print(), result, and complex_number::sub().
            {
   complex_number complex1(4, 5);
   complex_number complex2(7, -8);
   complex_number result(0,0);
   complex1.print();
   complex2.print();
   result.add(complex1,complex2);
   result.sub(complex1,complex2);
   return 0;
 }