Números Complejos: src/complejo.cc File Reference
complejo.cc File Reference
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
#include <iostream>
#include "complejo.h"
Variables
complex_number result (0, 0)
Detailed Description
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Author
Alejandro García Bautista
Date
27/12/20 Todas las funciones pertenecientes a la clase complex_number que son necesarias para poder sumar y restar dos números complejos
Bug:
Ninguno conocido por el momento.
Definition in file complejo.cc.
Variable Documentation
result
complex_number result(0, 0)
Referenced by complex_number::complex_number(), main(), and TEST().